# sudo apt install tmuxinator
# place this file in ".tmuxinatior.yml" then from that directory enter the command "mux"

# export WORKSPACE=/var/lib/jenkins-agent/workspace/aim-platform_production/image-archive/

name: AIM
windows:
  -  PROD: ''
  -  elastic: 
      layout: tiled
      root: <%= ENV["WORKSPACE"] %>/elastic-search
      panes:
        - sudo docker logs -f elasticsearch
        - curl -H 'Content-Type: application/json' -v http://192.168.136.148:9200/movieappfinal/_search?scroll=5m -d '{"query":{"match_all":{}}}' | jq
  - dejavu: 
      layout: tiled
      root: <%= ENV["WORKSPACE"] %>/elastic-search
      panes:
        - echo 'sudo docker run -p 1358:1358 -d appbaseio/dejavu'
        - echo 'http://localhost:1358/'
  - dwv:
      root: <%= ENV["WORKSPACE"] %>/dwv
      layout: tiled
      panes:
        - yarn run start
        - echo 'http://192.168.136.148:8080/index.html?input=http://192.168.136.148:3000/static/92939506.dcm'
  - react:
      root: <%= ENV["WORKSPACE"] %>/reactive-search
      layout: tiled
      panes:
        - source ../environments/production/env.sh && npm run dev
        - echo 'http://localhost:3000'
  - deid:
      root: <%= ENV["WORKSPACE"] %>/de-id
      layout: tiled
      panes:
        - . activate; "#python load_elastic.py"
        - . activate;
  - apache:
      root: /etc/apache2
      layout: tiled
      panes:
        - sudo vim /etc/apache2/sites-enabled/images.conf
        - sudo systemctl reload apache2
  - backup:
      layout: tiled
      panes:
        - ls -sh encrypted.tar.gz
        - watch ls -s encrypted.tar.gz
  - perf:
      layout: tiled
      panes:
        - "#htop"
        - "#iostat -xz 1"

