# sudo apt install tmuxinator
# tmuxinator --project-config=.tmuxinator.local.yml

name: AIM
root: ../../
windows:
  -  LOCAL: ''
  -  elastic:
      root: ../../elastic-search
      layout: tiled
      panes:
        - docker rm -f elasticsearch && docker run -d --name elasticsearch -p 9200:9200 -p 9300:9300 --env-file `pwd`/es-docker-env-vars -v `pwd`/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml -v /usr/share/elasticsearch/data docker.elastic.co/elasticsearch/elasticsearch:6.6.0
        - sleep 20 && source ../environments/local/env.sh && ./init_elastic.sh
  - dejavu: 
      layout: tiled
      panes:
        - docker run -p 1358:1358 -d appbaseio/dejavu
        - echo 'http://localhost:1358/'
  - dwv:
      root: ../../dwv/
      layout: tiled
      # prerequisite: yarn install
      panes:
        - yarn run start
        # - echo "http://192.168.136.148:8080/index.html?input=http://192.168.136.148:3000/static/92939506.dcm"
  - react:
      root: ../../reactive-search/
      layout: tiled
      # prerequisite: npm install
      panes:
        - source ../environments/local/env.sh && npm run dev
        - echo "http://localhost:3000"
  - deid:
      root: ../../de-id/
      layout: tiled
      panes:
        # - sleep 25 && source ../environments/local/env.sh && python3 load_elastic.py ../reactive-search/static/dicom/file_list.txt ../reactive-search/static/thumbnails/
        - sleep 20 && source ../environments/local/env.sh && python3 load_reports_elastic.py ../reports/sample/report_list # Load reports
        - sleep 30 && source ../environments/local/env.sh && python3 deid_dicoms.py --output_folder ~/aim-platform/image-archive/reactive-search/static/ --output_folder_suffix PHI --input_file ../images/sample/CT-MONO2-16-ort.dcm --fast_crop --input_base_path /home/dan/aim-platform/image-archive/images/ --input_report_base_path /home/dan/aim-platform/image-archive/reports/ --no_deidentify # Load PHI dicom
        - sleep 30 && source ../environments/local/env.sh && python3 deid_dicoms.py --output_folder ~/aim-platform/image-archive/reactive-search/static/ --output_folder_suffix DEID --input_file ../images/sample/CT-MONO2-16-ort.dcm --fast_crop --input_base_path /home/dan/aim-platform/image-archive/images/ --input_report_base_path /home/dan/aim-platform/image-archive/reports/ # Load DEID dicom